services:
  db:
    build: ./BBDD
    ports:
      - "3307:3307"
    networks:
      - my-network

  backend:
    build: ./BACK-END
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - db

  frontend:
    build: ./FRONT-END
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - db

networks:
  my-network:
    driver: bridge
